server:
  address: ":8002"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  serverRoot: "resource/public"
  clientMaxBodySize: 104857600  # 100MB in bytes 100*1024*1024

logger:
  level: "all"
  stdout: true

database:
  default:
    - type: "mysql"
      link: "root:123456@tcp(127.0.0.1:3306)/cooltest?charset=utf8mb4&parseTime=True&loc=Local"
      role: "master"
      debug: true
      createdAt: "createTime"
      updatedAt: "updateTime"
    - type: "mysql"
      link: "root:123456@tcp(127.0.0.1:3306)/cooltest?charset=utf8mb4&parseTime=True&loc=Local"
      role: "slave"
      debug: true
      createdAt: "createTime"
      updatedAt: "updateTime"
  default1:
    type: "sqlite"
    link: "./temp/db.sqlite"
    logLevel: "all"
    createdAt: "createTime"
    updatedAt: "updateTime"

# Redis 配置示例
redis:
  default:
    address: "127.0.0.1:6379"
    db: 0


cool:
  autoMigrate: true
  eps: true
  file:
    mode: "local"
    domain: "http://127.0.0.1:8002"

modules:
  base:
    jwt:
      sso: false
      secret: "cool-base88776655"
      token:
        expire: 7200 # 2*3600
        refreshExpire: 1296000 # 24*3600*15


