server:
  address: ":8001"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  clientMaxBodySize: 104857600 # 100MB in bytes 100*1024*1024

logger:
  level: "all"
  stdout: true

database:
  # default:
  #   type: "pgsql"
  #   host: "127.0.0.1"
  #   port: "5432"
  #   user: "cooltest"
  #   pass: "123456"
  #   name: "cooltest"
  #   debug: true
  #   createdAt: "createTime"
  #   updatedAt: "updateTime"
  default:
    type: "mysql"
    host: "127.0.0.1"
    port: "3306"
    user: "root"
    pass: "123456"
    name: "cooltest"
    charset: "utf8mb4"
    timezone: "Asia/Shanghai"
    debug: true
    createdAt: "createTime"
    updatedAt: "updateTime"
    deletedAt: "deleteTime"
  # default:
  #   type: "sqlite"
  #   link: "cool.sqlite"
  #   extra: busy_timeout=5000
  #   createdAt: "createTime"
  #   updatedAt: "updateTime"
  #   debug: true

# Redis 配置示例
redis:
  cool:
    address: "127.0.0.1:6379"
    db: 0

cool:
  autoMigrate: true
  eps: true
  file:
    mode: "local" # local | minio | oss
    domain: "http://127.0.0.1:8002"
    # oss配置项兼容 minio oss 需要配置bucket公开读
    oss:
      endpoint: "192.168.192.110:9000"
      accessKeyID: "accessKeyID"
      secretAccessKey: "secretAccessKey"
      bucketName: "cool-admin-go"
      useSSL: false #minio用到
      location: "us-east-1" #minio用到

modules:
  base:
    jwt:
      sso: false
      secret: "cool-base88776655"
      token:
        expire: 7200 # 2*3600
        refreshExpire: 1296000 # 24*3600*15
    middleware:
      authority:
        enable: true
      log:
        enable: true
