server:
  address:     ":8300"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  serverRoot: "coolweb"

logger:
  path: "./logs/"
  file: "{Y-m-d}.log"
  level : "all"
  stdout: true


database:
  autoMigrate: true
  default:
    type: "sqlite"
    link: "./data/db.sqlite"
    logLevel: "all"
    createdAt: "createTime"
    updatedAt: "updateTime"

cool-base:
  jwt:
    sso: false
    secret: "cool-admin-go-simple-secret"
    token:
      expire: 7200 # 2*3600
      refresh: 1296000 # 24*3600*15