server:
  address:     ":8300"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  serverRoot: "resource/public"
  clientMaxBodySize: 104857600  # 100MB in bytes 100*1024*1024

logger:
  path: "./logs/"
  file: "{Y-m-d}.log"
  level : "all"
  stdout: true


database:
  default:
    type: "sqlite"
    link: "./data/db.sqlite"
    logLevel: "all"
    createdAt: "createTime"
    updatedAt: "updateTime"

cool:
  autoMigrate: true
  file:
    mode: "local"
    domain: "http://127.0.0.1:8300"