server:
  address: ":8002"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  serverRoot: "./resource/public/dist"

logger:
  level: "all"
  stdout: true

database:
  autoMigrate: true
  default:
    - type: "mysql"
      link: "root:123456@tcp(127.0.0.1:3306)/cooltest?charset=utf8mb4&parseTime=True&loc=Local"
      role: "master"
      debug: true
      createdAt: "createTime"
      updatedAt: "updateTime"
    - type: "mysql"
      link: "root:123456@tcp(127.0.0.1:3306)/cooltest?charset=utf8mb4&parseTime=True&loc=Local"
      role: "slave"
      debug: true
      createdAt: "createTime"
      updatedAt: "updateTime"
  test:
    type: "sqlite"
    link: "./temp/db.sqlite"
    logLevel: "all"
    createdAt: "createTime"
    updatedAt: "updateTime"

# Redis 配置示例
redis:
  default:
    address: "127.0.0.1:6379"
    db: 0

cool-base:
  jwt:
    sso: false
    secret: "cool-base88776655"
    token:
      expire: 7200 # 2*3600
      refresh: 1296000 # 24*3600*15

